version: '3.9'
services:
  database:
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
  web:
    build: .
    command: sh -c "sleep 1 && python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py createsuperuser --noinput --username admin --email admin@example.com || true &&
                    python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SUPERUSER_PASSWORD: "test"
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - database